### ISSUE TITLE
Crash when typing "config"

### ISSUE THREAD

**Issue by VladTheEvilCat** [MCJack123/craftos2#290] opened 2022-11-04 16:27 UTC
**Describe the bug**
CraftOS-PC crashes when you type "config" into the default terminal.

**To Reproduce**
-Simply start the program and type "config" into the terminal.
-When you press "n", it crashes.

**Expected behavior**
It shouldn't crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/28151991/200025564-c0e61e99-65ea-4af6-b42c-b4b8df2880f3.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Enterprise
 - OS Version: 20H2
 - CraftOS-PC Version: 2.7.1
 - Compiled from source? No

 **Workaround**
 Press tab to autocomplete the config command instead of pressing 'n'.

**Comment by MCJack123** [comment] 2022-11-04 16:46
Duplicate of #280.

**Closed by MCJack123** 2022-11-04 16:46 UTC
Labels: bug
