### ISSUE TITLE
Computer on windows crashes when typing (or ending) path in shell in con, aux, prn (or any reserved keyword/filename on windows)

### ISSUE THREAD

**Issue by promitheas-nikou** [MCJack123/craftos2#296] opened 2022-12-06 17:32 UTC
To reproduce simply open a CraftOS computer on windows and (try to) type con. When pressing con, the program will crash.
Error: "Exception on computer thread: exists: The parameter is incorrect."

**Comment by MCJack123** [comment] 2022-12-06 19:58
Duplicate of #280.

**Closed by MCJack123** 2022-12-06 19:58 UTC
Labels: bug
