### ISSUE TITLE
CraftOS crashes on typing "con" in terminal (for changing config)

### ISSUE THREAD

**Issue by Xella37** [MCJack123/craftos2#293] opened 2022-11-22 17:54 UTC
**Describe the bug**
Open the emulator and type "con". The emulator now crashes.
I wanted to change a config setting so I feel like it might have to do with an autocompletion?
This happens on both normal CraftOS-PC as well as Accelerated and completely closing the emulator and restarting it does not help.

**To Reproduce**

CraftOS-PC:
1. Start emulator
2. Type "con"
3. The emulator now crashes with a popup with the exception message "Exception on computer thread: exists: The handle is invalid."

CraftOS-PC Accelerated:
1. Start emulator
2. Type "con"
3. The emulator now prints "C++ exception" in red, followed by "Goodbye" in yellow
4. The computer shuts down

**Expected behavior**
I expectthe emulator not to crash and to autocomplete with "config".

**Screenshots**

CraftOS-PC:
![image](https://user-images.githubusercontent.com/36447113/203385815-7276b78c-754d-45a1-9695-7c195e7ecb61.png)

CraftOS-PC Accelerated:
https://user-images.githubusercontent.com/36447113/203385838-6b8d03bd-3534-4e04-a2a5-374e564c3f0a.mp4

**Environment (please complete the following information):**
 - OS: Windows 10
 - OS Version: Version 10.0.19044 Build 19044
 - CraftOS-PC Version: v2.7.2
 - Compiled from source: No

**Comment by Xella37** [comment] 2022-11-22 18:03
Considering the following works, I'm fairly certain something is wrong with the autocomplete

https://user-images.githubusercontent.com/36447113/203388049-8712a656-fa98-4aa3-81da-05ba4402c885.mp4

**Comment by MCJack123** [comment] 2022-11-22 18:16
Duplicate of #280.

**Closed by MCJack123** 2022-11-22 18:16 UTC
Labels: bug
