### ISSUE TITLE
Crash when typing "con"

### ISSUE THREAD

**Issue by James-Dumas** [MCJack123/craftos2#295] opened 2022-12-06 01:13 UTC
**Describe the bug**
The emulator immediately crashes when I type "con" into the computer. I was attempting to use the "config" command. No other combination of characters that I have found causes the crash, just "con".

**To Reproduce**
1. Start the emulator
2. Type "con"

**Expected behavior**
The emulator probably shouldn't crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/22580418/205781426-4266b500-fda7-4c58-ae0f-190411a5db85.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - OS Version: 21H2
 - CraftOS-PC Version: v2.7.2
 - Compiled from source? No

**Additional context**
Here's the error message from the screenshot as text: "Exception on computer thread: exists: The handle is invalid."

**Comment by MCJack123** [comment] 2022-12-06 01:30
Duplicate of #280. However, since this is confirmed on v2.7.2 as well, I'll be reopening it.

**Closed by MCJack123** 2022-12-06 01:30 UTC
Labels: bug
