### ISSUE TITLE
Crashes on android

### ISSUE THREAD

**Issue by BlockOG** [MCJack123/craftos2#257] opened 2022-06-28 20:29 UTC
**Describe the bug**
When entering the latest version of CraftOS PC (2.6.6) on android it crashes (exits, doesn't give any crash report screen).

**To Reproduce**
1. Download and install latest version of CraftOS PC on android
2. Enter the app
3. See it exit immediately

**Expected behavior**
For the app to work properly.

**Environment (please complete the following information):**
 - OS: Android
 - OS Version: 12
 - CraftOS-PC Version: v2.6.6
 - Compiled from source? No

**Comment by MCJack123** [comment] 2022-07-12 02:33
Duplicate of #254

**Closed by MCJack123** 2022-07-12 02:33 UTC
Labels: bug, mobile
