### ISSUE TITLE
After fresh install, getting error after typing two characters

### ISSUE THREAD

**Issue by Erb3** [MCJack123/craftos2#302] opened 2022-12-18 18:30 UTC
**Describe the bug**
After installing a clean CraftOS-pc, and running it, it will quickly error after typing a few characters.

**To Reproduce**
1. Install CraftOS-PC
2. Start CraftOS-PC
3. Type a few characters

**Expected behavior**
I would have expected no error to come.

**Screenshots**
![image](https://user-images.githubusercontent.com/49862976/208313324-7f3614ec-4c4c-4fbc-9f53-457abfd785b9.png)

**Environment:**
 - OS: Windows 10
 - OS Version: 22H2
 - CraftOS-PC Version: v2.7.2
 - Compiled from source? No

**Comment by Ocawesome101** [comment] 2022-12-18 21:37
are those two characters `co`? because if so this issue will be fixed with v2.7.3.

**Comment by MCJack123** [comment] 2022-12-18 22:38
Duplicate of #280.

**Closed by MCJack123** 2022-12-18 22:38 UTC
Labels: bug
