### ISSUE TITLE
Web Version: Terminal Smaller Than Window

### ISSUE THREAD

**Issue by Tomodachi94** [MCJack123/craftos2#173] opened 2020-12-27 00:35 UTC
**Describe the bug**
The "screen" part with the terminal is smaller than the designated area (the yellow box).

**To Reproduce**
1. Go to 'https://www.craftos-pc.cc/online/'

**Expected behavior**
I expected the "screen" to fill the window

**Supplemental Media**
![image](https://user-images.githubusercontent.com/68489118/103161546-40a3a680-4798-11eb-8a0b-0822bffc2ec5.png)
======================================

**Environment (please complete the following information):**
 - OS: Windows 10 via Brave Browser
 - CraftOS-PC Version: Latest Version on site
 - Compiled from source? No

**Comment by MCJack123** [comment] 2020-12-27 07:38
Duplicate of #156.

**Closed by MCJack123** 2020-12-27 07:38 UTC
Labels: bug, duplicate
